# Generated by Django 4.2.6 on 2023-10-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_all',
            name='about',
            field=models.TextField(max_length=150),
        ),
    ]
