# Generated by Django 4.2.6 on 2023-10-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_all_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_all',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
